### ISSUE TITLE
Circos plot not working

### ISSUE THREAD

**Issue by Sanewsg** [Rong-Zh/GWLD#4]
The circos plot code previously worked for me but until just recently does not. The duck data circos plots okay but it uses an example file not generated by myself. 
To prepare the data for a circos plot I generate an r2 matrix file of markers with R2 values, "r2<-LD(geno012, cores=1)" which returns infinite values for some markers in the matrix. I think this causes the problem.
Has anyone returned infinite values in their GWLD files and not been able to proceed? Any clues on what to check are appreciated.

**Comment by Rong-Zh** [comment]
I updated some parameters and [example.R](https://github.com/Rong-Zh/GWLD/blob/master/example/example.R) in the package. You can update the package version.
