### ISSUE TITLE
Issue with Installing the GWLD R Package

### ISSUE THREAD

**Issue by yogeshnaik3344** [Rong-Zh/GWLD#6]
I am encountering an issue while attempting to install the GWLD package on my system. The installation fails during the compilation step, and I receive the following error message:
![Screenshot (382)](https://github.com/user-attachments/assets/a9d4281d-c17f-42b6-a465-4948ae470d28)

**Comment by Rong-Zh** [comment]
Please install [Rtools](https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html) first.
